version: "3"

services:
  api:
    build: ./novelApi
    image: novel_api
    container_name: novelApi
    command: uwsgi --ini uwsgi.ini
    volumes:
      - api_data:/novelApi
    env_file:
      - ./novelApi/.env
    expose:
      - 8002
    networks:
      - nginx_network
networks:
  nginx_network:
    external: true
volumes:
  api_data: